//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using Smark.Data.Mappings;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


namespace log4netUTS.DAL {
    
    
    [Serializable()]
    [Table("Users")]
    public partial class Users : Smark.Data.Mappings.DataObject, IUsers {
        
        private string mID;
        
        public static Smark.Data.FieldInfo iD = new Smark.Data.FieldInfo("Users", "ID");
        
        private string mUserName;
        
        public static Smark.Data.FieldInfo userName = new Smark.Data.FieldInfo("Users", "UserName");
        
        private string mPassword;
        
        public static Smark.Data.FieldInfo password = new Smark.Data.FieldInfo("Users", "Password");
        
        private bool mIsLocked;
        
        public static Smark.Data.FieldInfo isLocked = new Smark.Data.FieldInfo("Users", "IsLocked");
        
        private bool mIsDeleted;
        
        public static Smark.Data.FieldInfo isDeleted = new Smark.Data.FieldInfo("Users", "IsDeleted");
        
        private DateTime mCreateTime;
        
        public static Smark.Data.FieldInfo createTime = new Smark.Data.FieldInfo("Users", "CreateTime");
        
        [ID()]
        [GUID_ID()]
        public virtual string ID {
            get {
                return this.mID;
            }
            set {
                this.mID = value;
                this.EntityState.FieldChange("ID");
            }
        }
        
        [Column("UserName")]
        public virtual string UserName {
            get {
                return this.mUserName;
            }
            set {
                this.mUserName = value;
                this.EntityState.FieldChange("UserName");
            }
        }
        
        [Column("Password")]
        public virtual string Password {
            get {
                return this.mPassword;
            }
            set {
                this.mPassword = value;
                this.EntityState.FieldChange("Password");
            }
        }
        
        [Column("IsLocked")]
        [BoolToInt()]
        public virtual bool IsLocked {
            get {
                return this.mIsLocked;
            }
            set {
                this.mIsLocked = value;
                this.EntityState.FieldChange("IsLocked");
            }
        }
        
        [Column("IsDeleted")]
        [BoolToInt()]
        public virtual bool IsDeleted {
            get {
                return this.mIsDeleted;
            }
            set {
                this.mIsDeleted = value;
                this.EntityState.FieldChange("IsDeleted");
            }
        }
        
        [Column("CreateTime")]
        [DatetimeToLong()]
        public virtual DateTime CreateTime {
            get {
                return this.mCreateTime;
            }
            set {
                this.mCreateTime = value;
                this.EntityState.FieldChange("CreateTime");
            }
        }
    }
}
